const express = require('express');
const dotenv = require('dotenv');
const cors = require('cors');
const connectDB = require('./config/db');
const authRoutes = require('./routes/auth');
const uploadRoutes = require('./routes/upload');
const chatbotRoutes = require('./routes/chatbot');
dotenv.config();
connectDB();
const app = express();
app.use(cors({ origin: '*'}));
app.use(express.json());
app.use('/auth', authRoutes);
app.use('/upload', uploadRoutes);
app.use('/chatbot', chatbotRoutes);
app.listen(8080, () => console.log('Server running'));
